import streamlit as st
import pandas as pd
import joblib
# === 1. Load model ===
model = joblib.load('house_price_model.pkl')

st.title("🏠 House Price Prediction")
st.write("Masukkan detail properti untuk memprediksi harga rumah.")

# === 2. Data referensi kota dan kodenya ===

city_mapping = {
    'Acton, CA': 1,
    'Agoura Hills, CA': 3,
    'Agua Dulce, CA': 4,
    'Alhambra, CA': 6,
    'Altadena, CA': 10,
    'Arcadia, CA': 16,
    'Artesia, CA': 19,
    'Arvin, CA': 20,
    'Azusa, CA': 23,
    'Bakersfield, CA': 24,
    'Baldwin Park, CA': 25,
    'Bear Valley Springs, CA': 28,
    'Bell Gardens, CA': 30,
    'Bell, CA': 31,
    'Bellflower, CA': 32,
    'Beverly Hills, CA': 35,
    'Boron, CA': 45,
    'Brawley, CA': 48,
    'Burbank, CA': 52,
    'Calabasas, CA': 54,
    'Calexico, CA': 55,
    'Caliente, CA': 56,
    'California City, CA': 57,
    'Canoga Park, CA': 62,
    'Canyon Country, CA': 63,
    'Carson, CA': 69,
    'Castaic, CA': 70,
    'Chatsworth, CA': 76,
    'Claremont, CA': 81,
    'Compton, CA': 85,
    'Covina, CA': 91,
    'Culver City, CA': 94,
    'Delano, CA': 99,
    'Diamond Bar, CA': 102,
    'Downey, CA': 103,
    'Eagle Rock, CA': 106,
    'East Los Angeles, CA': 107,
    'El Monte, CA': 111,
    'El Segundo, CA': 112,
    'Encino, CA': 114,
    'Frazier Park, CA': 122,
    'Gardena, CA': 125,
    'Glendale, CA': 126,
    'Glendora, CA': 127,
    'Gorman, CA': 129,
    'Granada Hills, CA': 130,
    'Green Valley, CA': 133,
    'Hacienda Heights, CA': 136,
    'Hawaiian Gardens, CA': 138,
    'Hermosa Beach, CA': 142,
    'Huntington Park, CA': 149,
    'Imperial, CA': 152,
    'Inglewood, CA': 155,
    'Inyokern, CA': 156,
    'Juniper Hills, CA': 162,
    'Keene, CA': 163,
    'Kernville, CA': 164,
    'La Canada Flintridge, CA': 165,
    'La Mirada, CA': 172,
    'La Puente, CA': 174,
    'La Verne, CA': 176,
    'Lake Elizabeth, CA': 184,
    'Lake Hughes, CA': 187,
    'Lake Los Angeles, CA': 188,
    'Lakewood, CA': 192,
    'Lancaster, CA': 193,
    'Lebec, CA': 196,
    'Leona Valley, CA': 198,
    'Littlerock, CA': 199,
    'Llano, CA': 200,
    'Long Beach, CA': 204,
    'Los Angeles, CA': 207,
    'Lynwood, CA': 211,
    'Malibu, CA': 212,
    'Mojave, CA': 220,
    'Monrovia, CA': 221,
    'Montebello, CA': 223,
    'Mt Baldy, CA': 232,
    'Newhall, CA': 239,
    'North Hollywood, CA': 245,
    'Northridge, CA': 247,
    'Norwalk, CA': 248,
    'Pacific Palisades, CA': 263,
    'Pacoima, CA': 264,
    'Palmdale, CA': 267,
    'Palos Verdes Estates, CA': 269,
    'Paramount, CA': 272,
    'Pasadena, CA': 274,
    'Pearblossom, CA': 277,
    'Pico Rivera, CA': 281,
    'Pine Mountain Club, CA': 282,
    'Playa del Rey, CA': 289,
    'Pomona, CA': 290,
    'Porter Ranch, CA': 292,
    'Quartz Hill, CA': 295,
    'Rancho Palos Verdes, CA': 301,
    'Redondo Beach, CA': 305,
    'Reseda, CA': 306,
    'Ridgecrest, CA': 308,
    'Rosamond, CA': 312,
    'Rowland Heights, CA': 315,
    'Salton City, CA': 317,
    'San Fernando, CA': 322,
    'San Gabriel, CA': 323,
    'San Marino, CA': 328,
    'San Pedro, CA': 330,
    'Santa Clarita, CA': 333,
    'Santa Monica, CA': 337,
    'Saugus, CA': 342,
    'Shadow Hills, CA': 344,
    'Sherman Oaks, CA': 346,
    'Sierra Madre, CA': 347,
    'South El Monte, CA': 353,
    'South Gate, CA': 354,
    'South Pasadena, CA': 355,
    'Stallion Springs, CA': 357,
    'Stevenson Ranch, CA': 359,
    'Studio City, CA': 360,
    'Sunland, CA': 364,
    'Sylmar, CA': 365,
    'Tarzana, CA': 366,
    'Tehachapi, CA': 367,
    'Temple City, CA': 369,
    'Toluca Lake, CA': 374,
    'Torrance, CA': 376,
    'Tujunga, CA': 378,
    'Val Verde, CA': 382,
    'Valley Glen, CA': 385,
    'Valley Village, CA': 386,
    'Van Nuys, CA': 387,
    'Venice, CA': 389,
    'Walnut, CA': 395,
    'West Covina, CA': 397,
    'West Hollywood, CA': 399,
    'Westchester, CA': 400,
    'Whittier, CA': 404,
    'Wilmington, CA': 406,
    'Wofford Heights, CA': 409,
    'Woodland Hills, CA': 410,
}

# === 3. Input parameter lain ===
bed = st.number_input("Jumlah Kamar Tidur (bed)", min_value=1, max_value=10, value=3)
bath = st.number_input("Jumlah Kamar Mandi (bath)", min_value=1, max_value=10, value=2)
sqft = st.number_input("Luas Bangunan (sqft)", min_value=200, max_value=10000, value=1500)

# === 4. Input lokasi (dropdown kota) ===
citi = st.selectbox("Pilih Kota", list(city_mapping.keys()))


# === 5. Siapkan input DataFrame untuk prediksi ===
input_data = pd.DataFrame({
    'bed': [bed],
    'bath': [bath],
    'sqft': [sqft],
    'citi': [citi]
})

# === 6. Prediksi harga ===
if st.button("Prediksi Harga Rumah"):
    prediction = model.predict(input_data)
    st.success(f"💰 Perkiraan Harga Rumah: ${prediction[0]:,.3f}")
